### PR TITLE
Add an additional 'AppendedVersioning' trait

### PR DESCRIPTION
**Pull request by EspadaV8**
The new trait changes the way versions are saved so that instead of
creating a new record with a new primary key, the newly created record
is actually the old, pre-edited record. The changes are then saved to
the existing record to maintain the primary key.

This is in reference to #14 and #15 . It completely changes the way that versioning happens but should do so in a transparent way for the user. All existing tests pass for this new trait.

### CODE REVIEW

**Comment by sbarre** [comment]
This is great.  I think this should possibly be the way the regular trait works as well.  Can you think of any reason why "normal" versioning should not be "make a copy then update in place"?  

If this solves the foreign key issue (which had me a bit stumped), and doesn't affect other use cases, then let's make it that way all the time.

**Comment by EspadaV8** [comment]
I can't think of any issues with the way this works at the moment, but I've only been testing on a development environment.

I'm not sure if switching to this method would work with a database that already had existing versions in it so if it did become the default it'd need a major version bump (I know < 1.0 things can break but probably safer to go to `0.1.0` instead of `0.0.8`).

If this were to come the default I'm happy to update the commits so that it changes the standard `Versioned` trait, but if possible could some of the previous PRs get checking/pulled first? #9, #10 and #11 would be the main ones and #7 would be nice too if you're happy with the updated behaviour.

**Comment by EspadaV8** [comment]
Actually, one thing I've just thought of, if this was going to become the default way of versioning then I'd like to make some changes to the `model_id` usage. Outside of the trait I don't think it needs to be exposed, it would only be used by us as a way to group all of the past versions.

This would make it much easier to work with standard Laravel relations (at the moment for many-to-many relationships I need to hack a way to get the actual ID of the model since the `model_id` doesn't work).

**Comment by sbarre** [comment]
Hmm in my testing the many-to-many relations worked fine with `model_id`.   I'll have to take a closer look at that.  Do you have Gist or a paste somewhere that shows how you're running into that problem?

I agree about incrementing to 0.1.0, that's likely what I was going to do once I tested for L5.1 anyways.

**Comment by EspadaV8** [comment]
How did you get a many-to-many on the model_id? Foreign keys need to go to a unique id (which is normally the primary key).

I've not got a (real) example to hand (back at home now), but I can't see any way it could work

```
table_a

+----+----------+---------+------------+
| id | model_id | version | is_current |
+----+----------+---------+------------+
|  1 |        1 |       1 |          n |
|  2 |        1 |       2 |          y |
+----+----------+---------+------------+

table_b

+----+----------+---------+------------+
| id | model_id | version | is_current |
+----+----------+---------+------------+
| 13 |       13 |       1 |          n |
| 14 |       13 |       2 |          n |
| 15 |       13 |       3 |          y |
+----+----------+---------+------------+

many_to_many

+------------+------------+
| table_a_id | table_b_id |
+------------+------------+
|          2 |         15 |
+------------+------------+

many_to_many_using_model_id

+------------------+------------------+
| table_a_model_id | table_b_model_id |
+------------------+------------------+
|                1 |               13 |
+------------------+------------------+
```

In this case using the `model_id` there's no way that the database can check that the foreign keys are actually correct since it could refer to any number of different records. This is part of what made me write the versioning like this, since once the actual `id` is constant it's much easier to work with many-to-many without needing to update the pivot table with the newly generated `id`s

**Comment by EspadaV8** [comment]
Oops, hit the wrong button then.

**Comment by EspadaV8** [comment]
The new commit just removes the leaking of the `model_id` to the outside world. Since a records ID doesn't change now there's no need to use the `model_id` anywhere except within our code to group items together.

**Comment by EspadaV8** [comment]
I've updated the PR so that the `AppendedVersioning` is now the default and only way.

**Pull request merged**
